---
title: "R Markdown Homework"
output: html_document
---
*Oguz Kirazdiken*

*28.09.2019*

```{r}
paste("Hello", "R Markdown!")
``` 

### About Me

  I completed my Bachelor with the study of "Industrial Engineering" at Bahcesehir University in 2017. Since, I have been working as a Purchasing Executive in Metro Cash & Carry. As a daily routine, I am always trying to gather data as much as possible from different resources to make accurate forecasts and inferences. For that matter, I realized that data science is a powerful knowledge which can help businesses by analyzing the mass data to attain information immediately.
  
  With this program, I will be able to implement modern techniques and methods of data analysis to get statistical inferences in my future profession. For further information you can check my [LinkedIn Profile](www.linkedin.com/in/oguz-kirazdiken).

***
  
### useR! 2019 Videos

[useR! 2019 Toulouse - Talk Forecasting - Eran Raviv](https://www.youtube.com/watch?v=8IIUvMXHJFs&t=587s)

  The video which linked above contains Eran Raviv's presentation about Forecast Combination in R with __ForecastComb__ package.Eran Raviv is one of the authors of ForecastComb package, [here](https://eranraviv.com) you can find more detailed information about him in his blog.
  
  At the beggining of his presentation, he mentioned about generally used forecasting models which executes simple average of different individual methods and added _"it works but not very intuitive"_. After that he explained their __OLS Combination__ in ForecastComb package.
  
  Basically in OLS combination, machine learns from every individual method's performance to put in which proportion(OLS weights) they should be added to calculation. After that he also mentions about what can ForecastComb package do for users and which widely used statistical techniques use forecast combination.He gave a summary list for what forecast combination can do;

* Accuracy Based Methods
  + Root mean square errors
  + Eigenvector Approach
* Regression based methods
  + OLS, LAD, CLS
  + Complete subset regressions

You can find his presentation [here](https://eranraviv.com/wp-content/uploads/2019/07/Toulouse/201907_toulouse.html#/).

***  

### Some interesting posts about R!

[‘Meta’ machine learning packages in R](https://towardsdatascience.com/meta-machine-learning-packages-in-r-c3e869b53ed6)

  This post mentions about an figurative ‘meta-package’ which can facilitate the deployment of multiple models in parallel, and then aggregate the results.The author tries to explain the consept with car driving analogy.
  
[A Gentle Introduction on Market Basket Analysis — Association Rules](https://datascienceplus.com/a-gentle-introduction-on-market-basket-analysis%E2%80%8A-%E2%80%8Aassociation-rules/)  

  There is a good example for how to perform Market Basket Analysis in R and how to interpret the results.Basically it looks for combinations of items that occur together frequently in transactions.

[From ‘R vs Python’ to ‘R and Python’](https://towardsdatascience.com/from-r-vs-python-to-r-and-python-aa25db33ce17)

  This document points out some high and low points for both of them and explains how we can utilize the strengths of both to end up with much better job.


